project:
  type: website
  # pre-render: R/pre_render.R
  render:
    - "*.qmd"
    - "!class_reports/"

website:
  title: "satellite-ground-truthing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: data_sources.qmd
        text: Data Sources

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

