project:
  type: website
  # pre-render: R/pre_render.R
  render:  # used to set render order
    - "data_sources/*.qmd"
    - "*.qmd"

website:
  title: "satellite-ground-truthing"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: data_sources.qmd
        text: Data Sources
      - href: class_reports/class_report_template.qmd
        text: mangroves

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

