---
title: "satellite-ground-truthing"
---

This repo outlines a set of habitat-class ground truth data aggregated by USF-IMaRS for use in training of satellite image processing routines.
Data provided by different sources is overviewed and standardized in the "Data Sources" reports.
An exploration of the optical properties of each class is in "Class Reports".

# example data usage
```{r setup}
# Install librarian package if you haven't already
if (!requireNamespace("librarian", quietly = TRUE)) {
  install.packages("librarian")
}
library(librarian)
shelf(
  dplyr,
  here,
  leaflet
)
```
Load NERRS data

```{r}
data <- csv.read(here("data/dwc/mangrove-jobos.csv"))
```

```{r}
#| code-summary: create map 
# Create a color palette
pal <- colorFactor(palette = "viridis", domain = data$occurrenceStatus)

# Create the leaflet map
leaflet(data) %>%
  addTiles() %>%
  addCircleMarkers(
    ~lon, ~lat,
    color = ~pal(occurrenceStatus),
    radius = 5,
    fillOpacity = 0.8,
    popup = ~paste("Occurrence Status:", occurrenceStatus)
  ) %>%
  addLegend(
    "bottomright", pal = pal, values = ~occurrenceStatus,
    title = "Occurrence Status",
    opacity = 1
  )
```
